--INSERT INTO tb_tarefas (descricao, tarefa_status) VALUES ('fazer a compra do mês', 'P');
--INSERT INTO tb_tarefas (descricao, tarefa_status) VALUES ('pagar aa contas do mês', 'F');
--INSERT INTO tb_tarefas (descricao, tarefa_status) VALUES ('lavar o tapete', 'F');
--INSERT INTO tb_tarefas (descricao, tarefa_status) VALUES ('eletrica Tia Marta', 'E');
--INSERT INTO tb_tarefas (descricao, tarefa_status) VALUES ('preguiça', 'C');